#                       IPython
alias ii="ipython3 -i"
alias lk="python3 ~/IPython/chmod.py"
alias pdcsv="ipython3 -i ~/IPython/Pandas_read_CSV.py"
alias pdprq="ipython3 -i ~/IPython/Pandas_read_parquet.py"
alias pscsv="ipython3 -i ~/IPython/PySpark_read_CSV.py"
alias psprq="ipython3 -i ~/IPython/PySpark_read_parquet.py"
alias psmysql="ipython3 -i ~/IPython/PySpark_MySQL.py"
alias psrs="ipython3 -i ~/IPython/PySpark_RedShift.py"
alias eqry="ipython3 -i ~/IPython/MySQL_ex_query.py"
alias qry="ipython3 -i ~/IPython/MySQL_input_query.py"
alias rsq="ipython3 -i ~/IPython/RedShift_input_query.py"
alias eJson="ipython3 ~/IPython/Encrypt_JSON.py"
alias eJ="ipython3 ~/IPython/Encrypt_JSON.py"
alias dJ="ipython3 ~/IPython/Decrypt_JSON.py"
alias psq="ipython3 -i ~/IPython/PySpark_MySQL.py"
alias bsrBck="ipython3  ~/IPython/bck_bashrc.py"
alias ydl="python /home/roberto/IPython/ydl.py"
alias speak="python /home/roberto/IPython/speak.py"
alias S="python /home/roberto/IPython/speak.py"

