#                       IPython
alias ii="ipython3 -i"
alias lk="python3 ~/IPython/chmod.py"
alias pdr="ipython3 -i ~/IPython/Pandas_read_CSV.py"
alias psr="ipython3 -i ~/IPython/PySpark_read_CSV.py"
alias eqry="ipython3 -i ~/IPython/MySQL_ex_query.py"
alias qry="ipython3 -i ~/IPython/MySQL_input_query.py"
alias rsq="ipython3 -i ~/IPython/RedShift_input_query.py"
alias eJson="ipython3 ~/IPython/Encrypt_JSON.py"
alias eJ="ipython3 ~/IPython/Encrypt_JSON.py"
alias dJ="ipython3 ~/IPython/Decrypt_JSON.py"
alias psq="ipython3 -i ~/IPython/PySpark_MySQL.py"
